# Generated by Django 4.1.7 on 2024-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
